import type { TaskProposal } from "@pipr/shared";

export function buildIssueBody(params: {
  goal: string;
  proposal: TaskProposal;
  agentRunId: string;
  decisionNote?: string;
}) {
  const { goal, proposal, agentRunId, decisionNote } = params;

  return `
## Goal
${goal}

## Proposal
${proposal.description ?? "_No description_"}

## Estimate
${proposal.estimate != null ? `${proposal.estimate}h` : "Not specified"}

## Provenance
${proposal.provenance.map((p) => `- ${p}`).join("\n")}

## Decision
${decisionNote ?? "_No decision note_"}

---
Generated by **pipr**
AgentRun: ${agentRunId}
`.trim();
}
